name: chat_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  cached_network_image: ^3.2.3
  get: ^4.6.5
  persistent_bottom_nav_bar:
  flutter_cache_manager: ^3.3.0
  firebase_core: ^2.4.1
  animated_text_kit: ^4.2.2
  firebase_auth: ^4.2.5
  email_validator: ^2.1.17
  image_picker: ^0.8.6+1
  cloud_firestore: ^4.3.1
  flutter_riverpod: ^2.1.3
  simple_circular_progress_bar: 
  firebase_storage: ^11.0.10
  flutter_keyboard_visibility: ^5.4.0
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true