// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpoYMnnZich95fmKQz9J4B8wVsHEMuHJw',
    appId: '1:125634621812:web:adec9f22c88395bd933c21',
    messagingSenderId: '125634621812',
    projectId: 'chatapp-92580',
    authDomain: 'chatapp-92580.firebaseapp.com',
    storageBucket: 'chatapp-92580.appspot.com',
    measurementId: 'G-1ED8QTVQK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE9nBF__hKrKdfPgfAaShLQ40bMn0hbRM',
    appId: '1:125634621812:android:ec8312f258f23476933c21',
    messagingSenderId: '125634621812',
    projectId: 'chatapp-92580',
    storageBucket: 'chatapp-92580.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuwTqOwMj9OH03dJ3IMjC0FeNP5ajA5Z4',
    appId: '1:125634621812:ios:9024ff95e7420210933c21',
    messagingSenderId: '125634621812',
    projectId: 'chatapp-92580',
    storageBucket: 'chatapp-92580.appspot.com',
    iosClientId: '125634621812-e9bvdifucbfd0q1p74ju06ddmre4b7dm.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuwTqOwMj9OH03dJ3IMjC0FeNP5ajA5Z4',
    appId: '1:125634621812:ios:9024ff95e7420210933c21',
    messagingSenderId: '125634621812',
    projectId: 'chatapp-92580',
    storageBucket: 'chatapp-92580.appspot.com',
    iosClientId: '125634621812-e9bvdifucbfd0q1p74ju06ddmre4b7dm.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
